---
services:
  database:
    image: postgres:16
    container_name: weather-forecast-postgres
    env_file: .env
    ports:
      - "${PGPORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  tg_bot:
    image: jackdemario/weather-forecast-bot
    container_name: weather-telegram-bot
    env_file: .env
    depends_on:
      database:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"
volumes:
  pgdata: