version: '3.8'

services:
  weather_forecasting_bot:
    image: jackdemario/weather-forecast-bot
    env_file: .env
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"