name: CI-Weather-Forecast-Bot
on:
  push:
    branches:
    - main
jobs:
    # Пока только проверка линтером. TODO: Добавить тесты
    tests:
      runs-on: ubuntu-24.04
      steps:
        - name: Check out the repo for "tests"
          uses: actions/checkout@v3

        - name: Install uv
          uses: astral-sh/setup-uv@v5
          with:
            version: "0.7.12"

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version-file: ".python-version"

        - name: Install flake8 and isort
          run: |
            uv add install flake8 isort

        - name: Run flake8
          run: |
            flake8 ./src

        - name: Run isort
          run: |
            isort ./src --check --diff

    build_and_push_to_dockerhub:
      runs-on: ubuntu24.04
      needs: tests
      steps:
        - name: Check out the repo for build
          uses: actions/checkout@v3

        - name: Install uv
          uses: astral-sh/setup-uv@v5
          with:
            version: "0.7.12"

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version-file: ".python-version"

        - name: Install dependencies and flake8, isort
          run: |
            uv sync --locked --all-extras --dev

        - name: Install Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD}}

        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/weather-forecast-bot:latest
